# Generated by Django 6.0.2 on 2026-02-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
